# Generated by Django 5.1.7 on 2025-03-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applicantCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='deptCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SchemeDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.TextField()),
                ('open_date', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('implementing_agency', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('subcategory', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('brief_description', models.TextField(blank=True, null=True)),
                ('detailed_description', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('exclusions', models.TextField(blank=True, null=True)),
                ('eligibility_criteria', models.TextField(blank=True, null=True)),
                ('application_process', models.TextField(blank=True, null=True)),
                ('documents_required', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='yearCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
