# Generated by Django 5.1.7 on 2025-03-31 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eamiddleware', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='applicantcounts',
            table='applicantCounts',
        ),
        migrations.AlterModelTable(
            name='deptcounts',
            table='deptCounts',
        ),
        migrations.AlterModelTable(
            name='schemedirectory',
            table='schemeDirectory',
        ),
        migrations.AlterModelTable(
            name='yearcounts',
            table='yearCounts',
        ),
    ]
